### ISSUE TITLE
Rename Project and Tool

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/cpu-energy-meter#1]
We must not continue to use the name "Intel Power Gadget". Also this tool is not BenchExec-specific.

**Comment by PhilippWendler** [comment]
The new name is `cpu-energy-meter`. At least the documentation and the name of the binary need to be adapted.

**Comment by TBunk** [comment]
Done in commit 934868cd5b6f3dfb582f6747b7e9b71f0dc8b7fc. The 'README.md' has been updated accordingly.
