### ISSUE TITLE
Optimize measurements

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/cpu-energy-meter#10]
We want the measurements to work with as little overhead as possible. Currently for every single measurement (i.e., four times per cpu per measurement interval) the device file in `/dev/` is opened. This could be optimized at least to read all values at once, or even just opening the file during initialization and then reusing the same file descriptor.

This should be done after #9.

**Comment by TBunk** [comment]
Done in commit 9a3dbe2dd5ed28061326f00acd6de70211bd408b.
