### ISSUE TITLE
Check with official documentation whether we do everything correctly

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/cpu-energy-meter#13]
I found the official documentation for the Intel RAPL interface in the [Intel Software Developers Manual Volume 3B Chapter 14.9](https://software.intel.com/sites/default/files/managed/7c/f1/253669-sdm-vol-3b.pdf). The processor-specific documentation (which domains are supported on what CPU model, what the address of the MSRs is) can be found in [Volume 3C Chapter 35](https://software.intel.com/sites/default/files/managed/7c/f1/326019-sdm-vol-3c.pdf). The page that always links to the current versions of these PDFs is [here](https://software.intel.com/en-us/articles/intel-sdm).

We should check whether the tool reads everything correctly according to the documentation. Maybe we can also extend it to more CPU models.

**Comment by PhilippWendler** [comment]
There are also papers available about this topic, e.g. [An Energy Efficiency Feature Survey of the
Intel Haswell Processor](https://tu-dresden.de/zih/forschung/ressourcen/dateien/laufende-projekte/firestarter/2015_hackenberg_hppac.pdf). This paper also mentions that for some CPUs the units we use might be wrong, cf. https://github.com/RRZE-HPC/likwid/issues/39.

**Comment by PhilippWendler** [comment]
More information can also be found in the [Linux kernel](http://lxr.free-electrons.com/source/arch/x86/events/intel/rapl.c).

**Comment by PhilippWendler** [comment]
A nice summary is also in a [blog post from Intel](https://01.org/blogs/2014/running-average-power-limit-–-rapl).

**Comment by TBunk** [comment]
According to [Intel Software Developers Manual Volume 4, Model-specific Registers](https://software.intel.com/sites/default/files/managed/22/0d/335592-sdm-vol-4.pdf), only CPU models from the Intel Gen. Sandybridge and onward support the power monitoring feature. I.e., the Core-, Core2-, Nehalem-, and Westmere-CPUs are excluded from that (among others). 
As for the "small core" processors (Atom), neither of the following are supported: Pineview, Lincroft, Penwell, Cloverview, Cedarview (Models 0x1C, 0x26, 0x27, 0x35, 0x36, respectively).

The changes for this issue can be found in https://github.com/sosy-lab/cpu-energy-meter/commit/b87ffbcee18f1220984c3960652cd3174f26623c, https://github.com/sosy-lab/cpu-energy-meter/commit/c264fa7f8d851106a9727949782e44bd84bcec00, and https://github.com/sosy-lab/cpu-energy-meter/commit/3118119c78971fa9a85260b2f5887051474272a7.

There is lots of duplicate code in the `init_rapl()`-method by now, though, I suggest to do the refactoring within the #9 task.
