### ISSUE TITLE
Switch machine- and human-readable mode

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/cpu-energy-meter#18]
The tool is still in beta and we do not need strict backwards compatibility, so I think we should make the human-readable output the default and provide a switch for machine-readable output, e.g., `-r` (for raw). This should then be documented in the help text.

**Comment by TBunk** [comment]
Implemented in commit 9a8a8c209fbe93a1da6626b8da9eebe3c53421ae. The help text is currently outdated and will be fixed within the next days.

**Comment by TBunk** [comment]
The help text has been updated in commit 8c94a41a9cb3e56110398187e9fb2c01672dfad8. I've set the current version to 1.0, however, that might need to be changed to a more fitting value.
