### ISSUE TITLE
missing info

### ISSUE THREAD

**Issue by slmatrix** [sosy-lab/cpu-energy-meter#23]
My i9 9900K is not reporting Uncore and PSYS energy numbers. Any ideas on why not?

**Comment by PhilippWendler** [comment]
In general the tool reports what the CPU produces as measurements, so it seems that the CPU maybe does not provide these values and cpu-energy-meter could not do more. But posting the output of running cpu-energy-meter with parameter `-d` could be useful.

`PSYS` is a measurement that depends not only on the CPU, but also on the system. So far I have only seen in on mainboards. Uncore should be present on CPUs with an integrated GPU though.

Maybe you could check with the [official Intel tool](https://software.intel.com/content/www/us/en/develop/articles/intel-power-gadget.html) which values it reports?

**Comment by slmatrix** [comment]
It seems Uncore does not show for a short run (few seconds). It works when I run the tool for many seconds.

Here is the output with `./cpu-energy-meter -d`:

> root@f3e7960d7e6e:~/cpu-energy-meter# ./cpu-energy-meter -d
> [DEBUG] GenuineIntel processor found.
> [DEBUG] Processor is from family 6 and uses model 0x906E0.
> [DEBUG] Using /dev/cpu/0/msr for accessing MSR of socket 0.
> [DEBUG] Domain Package is supported.
> [DEBUG] Domain Core is supported.
> [DEBUG] Domain Uncore is supported.
> [DEBUG] Domain DRAM is supported.
> [DEBUG] Domain PSYS is supported.
> [DEBUG] Measured the following unit multipliers:   RAPL_ENERGY_UNIT=6.103516e-05J   RAPL_DRAM_ENERGY_UNIT=6.103516e-05J
> [DEBUG] Max power consumption of node 0 is 95.000000W.
> [DEBUG] Interval time of msr probes set to 1378s, 0ns.
> [DEBUG] Time limit elapsed, reading values to ensure overflows are detected.
> [DEBUG] Time limit elapsed, reading values to ensure overflows are detected.
> ^C[DEBUG] Received signal 2.
> +--------------------------------------+
> | CPU Energy Meter            Socket 0 |
> +--------------------------------------+
> Duration               3083.460999 s
> Package               17696.206909 Joule
> Core                   3971.751648 Joule
> Uncore                    0.193359 Joule
> DRAM                   5769.442993 Joule


About `PSYS`, are you saying that some motherboards do not support the feature? I have an ordinary consumer Z390 mainboard.

**Comment by PhilippWendler** [comment]
> It seems Uncore does not show for a short run (few seconds). It works when I run the tool for tens of seconds.

This can happen because the resolution of the measurement is low in comparison to the energy consumption here.

> About `PSYS`, are you saying that some motherboards do not support the feature? I have an ordinary consumer Z390 mainboard. btw, thank you for replying.

My understanding is that most (all?) mainboards do not support this feature. I have only seen it on notebooks, so far.
