### ISSUE TITLE
Why the PSYS don't list?

### ISSUE THREAD

**Issue by dx2919717227** [sosy-lab/cpu-energy-meter#25]
OS:Ubuntu 18.04

[DEBUG] GenuineIntel processor found.
[DEBUG] Processor is from family 6 and uses model 0x906E0.
[DEBUG] Using /dev/cpu/0/msr for accessing MSR of socket 0.
[DEBUG] Domain Package is supported.
[DEBUG] Domain Core is supported.
[DEBUG] Domain Uncore is supported.
[DEBUG] Domain DRAM is supported.
[DEBUG] Domain PSYS is supported.
[DEBUG] Measured the following unit multipliers:   RAPL_ENERGY_UNIT=6.103516e-05J   RAPL_DRAM_ENERGY_UNIT=6.103516e-05J
[DEBUG] Max power consumption of node 0 is 95.000000W.
[DEBUG] Interval time of msr probes set to 1378s, 0ns.
^C[DEBUG] Received signal 2.
+--------------------------------------+
| CPU Energy Meter            Socket 0 |
+--------------------------------------+
Duration                166.440641 s
Package                 621.960876 Joule
Core                    337.406311 Joule
DRAM                    119.912598 Joule

The result lost PSYS,Is it the reason for the lack of dependences?or the PSYS is Disable.

**Comment by PhilippWendler** [comment]
What kind of system and which CPU is this? So far, I have seen `PSYS` only on laptops. Other CPUs might report that it is supported but always return zero values, which `cpu-energy-meter` then hides.

**Comment by PhilippWendler** [comment]
See also #23. If you want to make sure, you could double check with [Intel's tool](https://software.intel.com/content/www/us/en/develop/articles/intel-power-gadget.htmlhttps://software.intel.com/content/www/us/en/develop/articles/intel-power-gadget.html).

**Comment by dx2919717227** [comment]
thanks for your reply.
