### ISSUE TITLE
Gemini Lake Refresh 2019 supported

### ISSUE THREAD

**Issue by Threemages** [sosy-lab/cpu-energy-meter#26]
Does it support Gemini Lake Refresh (2019)

Because what I found from the code is 

#define CPU_INTEL_ATOM_GEMINI_LAKE      0x706A0     // Family 6 Model 122 (0x7a)

I am not sure if I can use the software in Gemini Lake Refresh CPU model. 

Brief introduction of Gemini Lake Refresh 2019
https://www.intel.com/content/www/us/en/products/docs/processors/pentium/pentium-celeron-desktop-brief.html

Thank you,

**Comment by PhilippWendler** [comment]
Did you test it? What happens?

I do not have such a CPU available, but I suspect that these CPUs should work just like the previous ones, we only might need to extend the list of supported CPUs in the source.

**Comment by Threemages** [comment]
> Did you test it? What happens?
> 
> I do not have such a CPU available, but I suspect that these CPUs should work just like the previous ones, we only might need to extend the list of supported CPUs in the source.

I don't have such a CPU neither. I was thinking to buy an Odroid H2 board which has Gemini Lake Refresh CPU model. That's why I am looking for a proof that it could be run on the Gemini Lake Refresh one.

**Comment by PhilippWendler** [comment]
In principle, this should be described in the [Intel Software Developer's Manual](https://software.intel.com/content/www/us/en/develop/articles/intel-sdm.html#three-volume). Volume 4 describes which MSRs are available on each generation. Can you search for your CPU in this document? I searched for "Gemini" but this term is not found, so one needs to identify the CPU via some other mechanism like family and model ids. Note that the document does not only contain Atom CPUs, but also Core and Xeons, so these must not be confused.

If you find your CPU, search for MSRs named `MSR_DRAM_*`, `MSR_PKG_*` etc. and check their description for any specific information. If you can tell me on which page the CPU is listed, I can also double-check the info.

**Comment by Threemages** [comment]
> In principle, this should be described in the [Intel Software Developer's Manual](https://software.intel.com/content/www/us/en/develop/articles/intel-sdm.html#three-volume). Volume 4 describes which MSRs are available on each generation. Can you search for your CPU in this document? I searched for "Gemini" but this term is not found, so one needs to identify the CPU via some other mechanism like family and model ids. Note that the document does not only contain Atom CPUs, but also Core and Xeons, so these must not be confused.
> 
> If you find your CPU, search for MSRs named `MSR_DRAM_*`, `MSR_PKG_*` etc. and check their description for any specific information. If you can tell me on which page the CPU is listed, I can also double-check the info.

I think the board (Odroid HC2+ x86 https://wiki.odroid.com/odroid-h2/start#tab__h2_j4115) I am looking at now is Goldmont Plus (https://en.wikipedia.org/wiki/Goldmont_Plus#:~:text=Goldmont%20Plus%20is%20a%20microarchitecture,platform%20on%20November%204%2C%202019.). 
It is on page 2-114. Table 2-13. But I am not sure how to check the specific CPU. The CPU in that board is J4115.

**Comment by PhilippWendler** [comment]
The CPUs for which Table 2-13 is relevant (which starts on page 2-119 for me) indeed should support RAPL, because Table 2-13 includes Table 2-12 in its last line, and Table 2-12 mentions the RAPL registers on page 2-110.

Note that Table 2-13 is for family 6 model 0x7a, which is the same as the definition of `CPU_INTEL_ATOM_GEMINI_LAKE` that you quoted. According to Wikipedia, both Gemini Lake and Gemini Lake Refresh are part of Goldmont Plus, so this would fit. And anyway, both the predecessor generation Goldmont and the successor generation Tremont also should support RAPL (cf. Table 2-12 and Table 2-14, respectively).

I cannot find any CPU named J4115, though, neither on Wikipedia nor on the [Intel CPU database](https://ark.intel.com/content/www/us/en/ark/products/series/77504/intel-celeron-processor-j-series.html).

**Comment by Threemages** [comment]
> The CPUs for which Table 2-13 is relevant (which starts on page 2-119 for me) indeed should support RAPL, because Table 2-13 includes Table 2-12 in its last line, and Table 2-12 mentions the RAPL registers on page 2-110.
> 
> Note that Table 2-13 is for family 6 model 0x7a, which is the same as the definition of `CPU_INTEL_ATOM_GEMINI_LAKE` that you quoted. According to Wikipedia, both Gemini Lake and Gemini Lake Refresh are part of Goldmont Plus, so this would fit. And anyway, both the predecessor generation Goldmont and the successor generation Tremont also should support RAPL (cf. Table 2-12 and Table 2-14, respectively).
> 
> I cannot find any CPU named J4115, though, neither on Wikipedia nor on the [Intel CPU database](https://ark.intel.com/content/www/us/en/ark/products/series/77504/intel-celeron-processor-j-series.html).

Thank you very much for your help. Appreciate it.
