### ISSUE TITLE
Sampling delay must be greater than 50 ms.

### ISSUE THREAD

**Issue by nricciardi** [sosy-lab/cpu-energy-meter#32]
I have installed the last version of this software (CPU Energy Meter v1.2), but when I try to run it using `-e` option it returns
```
Sampling delay must be greater than 50 ms.
```
whatever I use as value.

Below an example.

```
$ cpu-energy-meter -e=1
Sampling delay must be greater than 50 ms.

$ cpu-energy-meter -e=10000
Sampling delay must be greater than 50 ms.

$ cpu-energy-meter -e=10000000
Sampling delay must be greater than 50 ms.
```

I think this is a bug.

**Comment by PhilippWendler** [comment]
Right, thanks for reporting. The syntax with `=` was documented but did not work, only `-e100` and `-e 100`. Now `-e=100` works as well.
