### ISSUE TITLE
Provide Debian Package

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/cpu-energy-meter#6]
We should build a Debian package that can be used to install the tool, and (optionally) ensures that the necessary modules are loaded.

**Comment by TBunk** [comment]
I've rechecked that the Debian packaging still works with all the recent changes made to the directory structure in commit 09fe41db58e2138983faf0431ec53ffdb50c47c5.

A quick generation of a .deb file within the current project is as follows [description taken from commit 5b7c288030f4154b8eceb55ed7bf1e91b7c5260b]:
1.) 'make dist',
2.) 'dh_make -f cpu-energy-meter-1.1-dev.tar.gz -p cpu-energy-meter-1.1',
    with the version number changed accordingly, and
3.) dpkg-buildpackage -us -uc

Note that for the third command to be executed successfully, the `debian/changelog` file needs to be changed such that the version number corresponds with the version number given in the -p argument on the second line, and that the distribution is set to something which is accepted by `dh_make`, like e.g. unstable.

**Comment by TBunk** [comment]
Done as of March, 2018. 

PS: I've written a comprehensive short-guide on how to setup a project such that it allows a quick generation of deb-files that fits to our needs. Maybe I can present that to you within the upcoming days or weeks, @PhilippWendler .

**Comment by PhilippWendler** [comment]
There is now also [`scripts/create_deb.sh`](https://github.com/sosy-lab/cpu-energy-meter/blob/master/scripts/create_deb.sh), which automates this. Our GitLab CI builds the Debian package for every push, and one can download it from [there](https://gitlab.com/sosy-lab/software/cpu-energy-meter/pipelines).
