### ISSUE TITLE
Terminates with exit code 2

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/cpu-energy-meter#8]
If `cpu-energy-meter` receives a `SIGINT` directly after being started, it terminates with exit code 2. It should instead terminate gracefully with the expected output.

**Comment by leostrakosch** [comment]
Could you check whether commit 80862833 solves this for you? For me it works as intended after that commit.

**Comment by PhilippWendler** [comment]
Thanks, looks good.

Btw., if you mention the issue number in the commit message, GitHub can automatically reference the commit and the issue.
